backend:
  image:
    repository: 433193941125.dkr.ecr.ap-south-1.amazonaws.com/movie-backend
    tag: "16"
    env:
    DB_HOST: "movie-analyzer-db.crimuwie2ihu.ap-south-1.rds.amazonaws.com"
    DB_NAME: "moviereviews_dev"
    DB_PORT: "5432"
    
frontend:
  image:
    repository: 433193941125.dkr.ecr.ap-south-1.amazonaws.com/movie-frontend
    tag: "16"

model:
  image:
    repository: 433193941125.dkr.ecr.ap-south-1.amazonaws.com/movie-model
    tag: "16"


ingress:
  host: dev.movie-analyzer.internal

dbInit:
  enabled: false
  user: movieuser

