backend:
  image:
    repository: 433193941125.dkr.ecr.ap-south-1.amazonaws.com/movie-backend
    tag: "14"
  env:
    DB_HOST: "moviereviews-instance.cnku6m4wm4rj.ap-south-1.rds.amazonaws.com"
    DB_NAME: "moviereviews_dev"

frontend:
  image:
    repository: 433193941125.dkr.ecr.ap-south-1.amazonaws.com/movie-frontend
    tag: "15"

model:
  image:
    repository: 433193941125.dkr.ecr.ap-south-1.amazonaws.com/movie-model
    tag: "15"

ingress:
  host: dev.movie-analyzer.internal
